import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/next-auth/SessionProvider";
import { getServerSession } from "next-auth";
import { ModalProvider } from "@/context/ModalContext";
import LoginModal from "@/components/user/login/LoginModal";
import MynavBar from "@/components/UI/MyNavbar";

const mitr = Mitr({
  weight: "300",
  subsets: ["latin", "thai"],
});
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "TripGether",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <SessionProvider session={session}>
        <body className={inter.className}>
          <Toaster />
          <ModalProvider>
            <MynavBar />
            {children}
            <LoginModal />
          </ModalProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
