import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/next-auth/SessionProvider";
import { getServerSession } from "next-auth";
import MynavBar from "@/components/UI/MyNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <SessionProvider session={session}>
        <body className={inter.className}>
          <MynavBar />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
